# Generated by Django 5.0.3 on 2024-07-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('raza', models.CharField(choices=[('B', 'Blanco'), ('N', 'Negro')], max_length=1)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EGeneral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=750)),
                ('fecha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egeneral', to='Historia.fecha')),
            ],
        ),
        migrations.CreateModel(
            name='EFaparato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pym_humedo', models.CharField(choices=[('S', 'Humeda'), ('N', 'No es Humeda')], max_length=1)),
                ('pym_coloreado', models.CharField(choices=[('S', 'Normocoloreado'), ('N', 'No es Normocoloreado')], max_length=1)),
                ('descripcion_pym', models.TextField(blank=True, null=True)),
                ('tvs', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('descripcion_tvs', models.TextField(blank=True, null=True)),
                ('inspeccion_respiratoria', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('palpacion_respiratoria', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('percusion_respiratoria', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('auscultacion_respiratoria', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_respiratoria', models.TextField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.CharField(max_length=255)),
                ('descripcion_frecuencia_respiratoria', models.TextField(blank=True, null=True)),
                ('inspeccion_cardiovascular', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('palpacion_cardiovascular', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('percusion_cardiovascular', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('auscultacion_cardiovascular', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_cardiovascular', models.TextField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.CharField(max_length=255)),
                ('presion_arterial', models.CharField(max_length=255)),
                ('pulso', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_fpp', models.TextField(blank=True, null=True)),
                ('inspeccion_abdominal', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('palpacion_abdominal', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('auscultacion_abdominal', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('percusion_abdominal', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_abdominal', models.TextField(blank=True, null=True)),
                ('conciente', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('orientado', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('descripcion_sn_central', models.TextField(blank=True, null=True)),
                ('signos_maningeos', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('descripcion_signos_maningeos', models.TextField(blank=True, null=True)),
                ('pares_craneales', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_pares_craneales', models.TextField(blank=True, null=True)),
                ('soma', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_soma', models.TextField(blank=True, null=True)),
                ('genital_urinario', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('genital_urinario_descripcion', models.TextField(blank=True, null=True)),
                ('mamas_simetricas', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('mamas_simetricas_descripcion', models.TextField(blank=True, null=True)),
                ('mamas_nodulos', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('mamas_nodulos_descripcion', models.TextField(blank=True, null=True)),
                ('estado_pezon', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('estado_pezon_descripcion', models.TextField(blank=True, null=True)),
                ('estado_axila', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('estado_axila_descripcion', models.TextField(blank=True, null=True)),
                ('genital_externo', models.CharField(choices=[('N', 'Normal'), ('P', 'Patológico')], max_length=1)),
                ('descripcion_genital_externo', models.TextField(blank=True, null=True)),
                ('peso', models.CharField(max_length=255)),
                ('talla', models.CharField(max_length=255)),
                ('orientacion', models.CharField(max_length=255)),
                ('proxima_cita', models.DateTimeField()),
                ('egeneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efaparato', to='Historia.egeneral')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efaparatos', to='Historia.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Interrogatorio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('antecedentes_personales', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('ap_personal_descripcion', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('ap_familiar_descripcion', models.TextField(blank=True, null=True)),
                ('h_toxicos', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('h_toxicos_descripcion', models.CharField(choices=[('T', 'Tabaco'), ('A', 'Alcohol'), ('D', 'Droga')], max_length=1)),
                ('alergias', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('alergias_descripcion', models.TextField(blank=True, null=True)),
                ('operaciones', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('operaciones_descripcion', models.TextField(blank=True, null=True)),
                ('transfuciones', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('transfuciones_descripcion', models.TextField(blank=True, null=True)),
                ('carnet_salud', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('carnet_salud_descripcion', models.DateTimeField(blank=True, null=True)),
                ('p_enfermedad', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('p_enfermedad_descripcion', models.TextField(blank=True, null=True)),
                ('ocupacion', models.CharField(choices=[('E', 'Estudiante'), ('T', 'Trabajador de la Cocina')], max_length=1)),
                ('ocupacion_descripcion', models.TextField(blank=True, choices=[('A', 'Ingeniero Informatico'), ('B', 'Ingeniero Mecanico'), ('C', 'Ingeniería Química'), ('D', 'Ingeniería Industrial'), ('E', 'Ingeniería en Transporte'), ('F', 'Ingeniería en Agronomía'), ('G', 'Ingeniería en Procesos Agroindustriales'), ('H', 'Licenciatura en Derecho'), ('I', 'Licenciatura en Economía'), ('J', 'Licenciatura en Contabilidad y Finanzas'), ('K', 'Licenciatura en Turismo'), ('L', 'Licenciatura en Educación Economía'), ('M', 'Licenciatura en Educación Matemática'), ('N', 'Licenciatura en Gestión Sociocultural para el Desarrollo'), ('O', 'Licenciatura en Comunicación Social'), ('P', 'Licenciatura en Cultura Física'), ('Q', 'Licenciatura en Educación. Construcción'), ('R', 'Licenciatura en Educación. Mecánica'), ('S', 'Licenciatura en Educación. Informática'), ('T', 'Licenciatura en Educación. Química'), ('U', 'Licenciatura en Educación Laboral'), ('V', 'Licenciatura en Educación Física'), ('W', 'Licenciatura en Historia'), ('X', 'Licenciatura en Educación. Marxismo-Leninismo e Historia'), ('Y', 'Licenciatura en Educación. Español-Literatura'), ('Z', 'Licenciaturas en Educación. Lenguas Extranjeras. Inglés'), ('1', 'Licenciatura en Educación Artística'), ('2', 'Licenciatura en Educación Especial'), ('3', 'Licenciatura en Educación. Logopedia'), ('4', 'Licenciatura en Educación Primaria'), ('5', 'Licenciatura en Educación Preescolar'), ('6', 'Licenciatura en Educación. Pedagogía-Psicología'), ('7', 'Licenciatura en Educación. Biología'), ('8', 'Licenciatura en Educación. Geografía'), ('9', 'Licenciatura en Educación Agropecuaria'), ('0', 'Medicina Veterinaria'), ('+', 'Técnico Superior en Gestión de la Innovación Agraria')], max_length=1, null=True)),
                ('egeneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interrogatorio', to='Historia.egeneral')),
            ],
        ),
        migrations.AddField(
            model_name='fecha',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='Historia.paciente'),
        ),
    ]
