# Generated by Django 5.1 on 2024-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0002_efaparato_indice_corporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efaparato',
            name='pulso',
            field=models.CharField(choices=[('P', 'Presente'), ('N', 'No Presente')], max_length=1),
        ),
    ]
