# Generated by Django 5.1 on 2024-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0004_alter_paciente_apellidos_alter_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=15),
        ),
    ]
