# Generated by Django 5.1 on 2024-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0005_alter_paciente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
    ]
