# Generated by Django 5.1.1 on 2024-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0008_alter_efaparato_indice_corporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogatorio',
            name='h_toxicos_descripcion',
            field=models.CharField(choices=[('T', 'Tabaco'), ('A', 'Alcohol'), ('D', 'Droga'), ('E', 'Tabaco y Alcohol'), ('K', 'Tabaco y Droga'), ('F', 'Alcohol y Droga')], max_length=1),
        ),
    ]
